services:
  
  # Servizio Redis (Aggiunto)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - ./bixengine/.env
    # Questo comando avvia Redis imponendo l'uso della password definita nel file .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Europe/Rome

  # Gunicorn
  web:
    build: .
    restart: unless-stopped
    env_file:
      - ./bixengine/.env
    volumes:
      - .:/app
      - ../uploads:/app/uploads
      - ../xml:/app/xml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8000:8000"
    command: gunicorn --bind 0.0.0.0:8000 bixengine.wsgi:application
    depends_on:
      - redis # Dice a Docker di avviare prima Redis e poi il Worker
    environment:
      - TZ=Europe/Rome

  # Servizio worker per i processi in backend
  qcluster:
    build: .
    restart: unless-stopped
    env_file:
      - ./bixengine/.env
    volumes: # volumi per la condivisione file con la macchina locale [posizione_macchina_locale:posizione_container]
      - .:/app
      - ../uploads:/app/uploads
      - ../xml:/app/xml
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: python manage.py qcluster
    depends_on:
      - redis # Dice a Docker di avviare prima Redis e poi il Worker
    environment:
      - TZ=Europe/Rome

volumes:
  redis_data: