# Generated by Django 5.0.9 on 2025-10-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0018_task_success_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_q.schedule')),
                ('send_to_endpoint', models.BooleanField(default=False, help_text='Send task data to endpoint')),
            ],
            options={
                'db_table': 'extended_schedule',
                'proxy': False,
            },
            bases=('django_q.schedule',),
        ),
    ]
