# Generated by Django 5.0.9 on 2025-10-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixscheduler', '0001_initial'),
        ('django_q', '0018_task_success_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to_endpoint', models.BooleanField(default=False, help_text='Send task data to endpoint')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='django_q.schedule')),
            ],
            options={
                'db_table': 'django_q_schedule_extra',
                'proxy': False,
            },
        ),
        migrations.DeleteModel(
            name='ExtendedSchedule',
        ),
    ]
