# Generated by Django 5.0.9 on 2025-12-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bixscheduler', '0002_scheduleextra_delete_extendedschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleextra',
            name='save_monitoring',
            field=models.BooleanField(default=False, help_text='Monitor the task'),
        ),
    ]
