# Generated by Django 5.0.9 on 2025-08-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp_swissbix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qrtoken',
            name='customapp_s_expires_1e53fd_idx',
        ),
        migrations.RemoveField(
            model_name='qrtoken',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='qrtoken',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='qrtoken',
            name='used_at',
        ),
    ]
