# Generated by Django 5.0.9 on 2025-09-05 12:18

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SysAutobatch',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(max_length=255)),
                ('tableid', models.CharField(blank=True, max_length=32, null=True)),
                ('crypted', models.CharField(max_length=1)),
                ('numfiles', models.IntegerField()),
                ('lastfileposition', models.IntegerField()),
                ('locked', models.CharField(max_length=1)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('originalpath', models.CharField(blank=True, max_length=255, null=True)),
                ('split', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_autobatch',
            },
        ),
        migrations.CreateModel(
            name='SysBatch',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(max_length=255)),
                ('tableid', models.CharField(blank=True, max_length=32, null=True)),
                ('crypted', models.CharField(max_length=1)),
                ('numfiles', models.IntegerField()),
                ('lastfileposition', models.IntegerField()),
                ('locked', models.CharField(max_length=1)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'sys_batch',
            },
        ),
        migrations.CreateModel(
            name='SysCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('field_data', models.CharField(blank=True, max_length=255, null=True)),
                ('field_orainizio', models.CharField(blank=True, max_length=255, null=True)),
                ('field_orafine', models.CharField(blank=True, max_length=255, null=True)),
                ('field_titolo', models.CharField(blank=True, max_length=255, null=True)),
                ('field_descrizione', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_condition', models.TextField(blank=True, null=True)),
                ('sync', models.IntegerField(blank=True, null=True)),
                ('userid_tosync', models.CharField(blank=True, max_length=255, null=True)),
                ('field_useridtosync', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_calendar',
            },
        ),
        migrations.CreateModel(
            name='SysDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order_dashboard', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sys_dashboard',
            },
        ),
        migrations.CreateModel(
            name='SysField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.CharField(max_length=255)),
                ('fieldid', models.CharField(max_length=255)),
                ('sync_fieldid', models.CharField(blank=True, max_length=255, null=True)),
                ('master_field', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_field', models.CharField(blank=True, max_length=255, null=True)),
                ('fieldtypeid', models.CharField(max_length=16)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('decimalposition', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('fieldorder', models.IntegerField(blank=True, null=True)),
                ('lookuptableid', models.CharField(blank=True, max_length=255, null=True)),
                ('lookupcodedesc', models.CharField(blank=True, max_length=1, null=True)),
                ('lookupdesclen', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(max_length=32)),
                ('tablelink', models.CharField(blank=True, max_length=32, null=True)),
                ('keyfieldlink', models.CharField(blank=True, max_length=128, null=True)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
                ('sublabel', models.CharField(blank=True, max_length=255, null=True)),
                ('showedbyvalue', models.CharField(blank=True, max_length=255, null=True)),
                ('showedbyfieldid', models.CharField(blank=True, max_length=255, null=True)),
                ('fieldtypewebid', models.CharField(blank=True, max_length=255, null=True)),
                ('linkfieldid', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_field',
            },
        ),
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ip', models.CharField(max_length=30)),
                ('pcname', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=30)),
                ('tableid', models.CharField(blank=True, max_length=30, null=True)),
                ('operationid', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('recordid', models.CharField(blank=True, max_length=32, null=True)),
                ('pageid', models.CharField(blank=True, max_length=32, null=True)),
                ('oldrecordid', models.CharField(blank=True, max_length=32, null=True)),
                ('oldpageid', models.CharField(blank=True, max_length=32, null=True)),
                ('sql', models.TextField(blank=True, null=True)),
                ('threadserverid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_log',
            },
        ),
        migrations.CreateModel(
            name='SysLogquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('funzione', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_logquery',
            },
        ),
        migrations.CreateModel(
            name='SysLookupTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('itemtype', models.CharField(blank=True, max_length=255, null=True)),
                ('codelen', models.IntegerField(blank=True, null=True)),
                ('desclen', models.IntegerField(blank=True, null=True)),
                ('numitems', models.IntegerField(blank=True, null=True)),
                ('linkfieldid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_lookup_table',
            },
        ),
        migrations.CreateModel(
            name='SysReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.CharField(blank=True, max_length=255, null=True)),
                ('fieldid', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('groupby', models.CharField(blank=True, max_length=255, null=True)),
                ('layout', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('custom', models.TextField(blank=True, null=True)),
                ('select_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('groupby_fields', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_report',
            },
        ),
        migrations.CreateModel(
            name='SysReportViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('viewid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('reportorder', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sys_report_views',
            },
        ),
        migrations.CreateModel(
            name='SysSchedulerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataora', models.DateTimeField(blank=True, null=True)),
                ('funzione', models.CharField(blank=True, max_length=255, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_scheduler_log',
            },
        ),
        migrations.CreateModel(
            name='SysSchedulerTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funzione', models.CharField(blank=True, max_length=255, null=True)),
                ('intervallo', models.IntegerField(blank=True, null=True)),
                ('limite', models.IntegerField(blank=True, null=True)),
                ('inizio', models.DateTimeField(blank=True, null=True)),
                ('fine', models.TimeField(blank=True, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('counter_limit', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('hours', models.CharField(blank=True, max_length=255, null=True)),
                ('minutes', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_scheduler_tasks',
            },
        ),
        migrations.CreateModel(
            name='SysSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('setting', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'sys_settings',
            },
        ),
        migrations.CreateModel(
            name='SysTable',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_service', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_table', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_field', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_order', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_type', models.CharField(blank=True, max_length=50, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('tabletypeid', models.IntegerField()),
                ('dbtypeid', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('lastrecordid', models.CharField(blank=True, max_length=32, null=True)),
                ('lastpageid', models.CharField(blank=True, max_length=32, null=True)),
                ('totpages', models.BigIntegerField(blank=True, null=True)),
                ('namefolder', models.CharField(max_length=5)),
                ('numfilesfolder', models.IntegerField()),
                ('mediaid', models.CharField(blank=True, max_length=32, null=True)),
                ('lastupdate', models.CharField(blank=True, max_length=14, null=True)),
                ('workspace', models.CharField(blank=True, max_length=256, null=True)),
                ('workspaceorder', models.IntegerField(blank=True, null=True)),
                ('tableorder', models.IntegerField(blank=True, null=True)),
                ('singular_name', models.CharField(blank=True, max_length=255, null=True)),
                ('plural_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_table',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('disabled', models.CharField(blank=True, max_length=1, null=True)),
                ('superuser', models.CharField(blank=True, max_length=1, null=True)),
                ('folder', models.CharField(blank=True, max_length=128, null=True)),
                ('folder_serverside', models.CharField(blank=True, max_length=256, null=True)),
                ('enablesendmail', models.IntegerField(blank=True, null=True)),
                ('bixid', models.IntegerField(blank=True, null=True)),
                ('hubspot_dealuser', models.CharField(blank=True, max_length=50, null=True)),
                ('adiutoid', models.IntegerField(blank=True, null=True)),
                ('lock_recordid', models.CharField(blank=True, max_length=45, null=True)),
                ('lock_tableid', models.CharField(blank=True, max_length=45, null=True)),
                ('lock_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='SysUserColumnWidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.CharField(blank=True, max_length=50, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('column_width', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'sys_user_column_width',
            },
        ),
        migrations.CreateModel(
            name='SysUserFavoriteTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_user_id', models.IntegerField(blank=True, null=True)),
                ('tableid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sys_user_favorite_tables',
            },
        ),
        migrations.CreateModel(
            name='SysUserPreferenceIndexTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('tableid', models.CharField(blank=True, max_length=32, null=True)),
                ('indexid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'sys_user_preference_index_table',
            },
        ),
        migrations.CreateModel(
            name='SysUserPreferencesLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('typepreference', models.CharField(blank=True, max_length=32, null=True)),
                ('dashboard', models.CharField(blank=True, max_length=32, null=True)),
                ('dati', models.CharField(blank=True, max_length=32, null=True)),
                ('allegati', models.CharField(blank=True, max_length=32, null=True)),
                ('tema', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'sys_user_preferences_layout',
            },
        ),
        migrations.CreateModel(
            name='SysUserSchedesalvate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.CharField(blank=True, max_length=32, null=True)),
                ('recordid', models.CharField(blank=True, max_length=32, null=True)),
                ('userid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_user_schedesalvate',
            },
        ),
        migrations.CreateModel(
            name='SysUserTableDefaultvalue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('tableid', models.CharField(blank=True, max_length=255, null=True)),
                ('fieldid', models.CharField(blank=True, max_length=255, null=True)),
                ('origintableid', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_param', models.CharField(blank=True, max_length=255, null=True)),
                ('defaultvalue', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_user_table_defaultvalue',
            },
        ),
        migrations.CreateModel(
            name='SysViewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('viewsql', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_view_report',
            },
        ),
        migrations.CreateModel(
            name='SysWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sys_widget',
            },
        ),
        migrations.CreateModel(
            name='SysAutobatchFile',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('fileext', models.CharField(max_length=6)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fileposition', models.IntegerField()),
                ('crypted', models.CharField(max_length=1)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('ocr', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_autobatch_file',
                'unique_together': {('batchid', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='SysBatchFile',
            fields=[
                ('fileid', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.CharField(max_length=32)),
                ('filename', models.CharField(max_length=32)),
                ('fileext', models.CharField(max_length=6)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fileposition', models.IntegerField()),
                ('crypted', models.CharField(max_length=1)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('ocr', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_batch_file',
                'unique_together': {('batchid', 'filename')},
            },
        ),
        migrations.CreateModel(
            name='SysLookupTableItem',
            fields=[
                ('lookuptableid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemcode', models.CharField(max_length=255)),
                ('itemdesc', models.CharField(blank=True, max_length=255, null=True)),
                ('linkvalue', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.IntegerField(blank=True, null=True)),
                ('itemorder', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sys_lookup_table_item',
                'unique_together': {('lookuptableid', 'itemcode')},
            },
        ),
        migrations.CreateModel(
            name='SysDashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('widgetid', models.IntegerField(blank=True, null=True)),
                ('width', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('gsx', models.IntegerField(blank=True, null=True)),
                ('gsy', models.IntegerField(blank=True, null=True)),
                ('gsw', models.IntegerField(blank=True, null=True)),
                ('gsh', models.IntegerField(blank=True, null=True)),
                ('calendarid', models.ForeignKey(blank=True, db_column='calendarid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.syscalendar')),
                ('dashboardid', models.ForeignKey(blank=True, db_column='dashboardid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysdashboard')),
                ('reportid', models.ForeignKey(blank=True, db_column='reportid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysreport')),
            ],
            options={
                'db_table': 'sys_dashboard_block',
            },
        ),
        migrations.CreateModel(
            name='SysCustomFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('results', 'Results'), ('card', 'Card')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('backend_app', models.CharField(max_length=100)),
                ('backend_function', models.CharField(max_length=100)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
            ],
            options={
                'verbose_name': 'Custom Function',
                'verbose_name_plural': 'Custom Functions',
                'db_table': 'sys_custom_function',
            },
        ),
        migrations.AddField(
            model_name='syscalendar',
            name='tableid',
            field=models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable'),
        ),
        migrations.CreateModel(
            name='SysAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_condition', models.TextField(blank=True, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_param', models.TextField(blank=True, null=True)),
                ('alert_user', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_description', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_fieldstocheck', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_viewid', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_order', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('alert_status', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
            ],
            options={
                'db_table': 'sys_alert',
            },
        ),
        migrations.CreateModel(
            name='SysTableFeature',
            fields=[
                ('tableid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('featureid', models.IntegerField()),
                ('enabled', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'sys_table_feature',
                'unique_together': {('tableid', 'featureid')},
            },
        ),
        migrations.CreateModel(
            name='SysTableLabel',
            fields=[
                ('tableid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('labelname', models.CharField(max_length=32)),
                ('labelorder', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_table_label',
                'unique_together': {('tableid', 'labelname')},
            },
        ),
        migrations.CreateModel(
            name='SysTableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingid', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
            ],
            options={
                'db_table': 'sys_table_settings',
            },
        ),
        migrations.CreateModel(
            name='SysTableSublabel',
            fields=[
                ('tableid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sublabelname', models.CharField(max_length=32)),
                ('sublabelorder', models.SmallIntegerField(blank=True, null=True)),
                ('showedbytableid', models.CharField(blank=True, max_length=255, null=True)),
                ('showedbyfieldid', models.CharField(blank=True, max_length=255, null=True)),
                ('showedbyvalue', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_table_sublabel',
                'unique_together': {('tableid', 'sublabelname')},
            },
        ),
        migrations.CreateModel(
            name='SysTableWorkspace',
            fields=[
                ('workspaceid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_table_workspace',
            },
        ),
        migrations.CreateModel(
            name='SysGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creatorid', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('disabled', models.CharField(blank=True, max_length=1, null=True)),
                ('idmanager', models.ForeignKey(blank=True, db_column='idmanager', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_group',
            },
        ),
        migrations.AddField(
            model_name='syscalendar',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser'),
        ),
        migrations.CreateModel(
            name='SysUserDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('order', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('dashboardid', models.ForeignKey(blank=True, db_column='dashboardid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysdashboard')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_dashboard',
            },
        ),
        migrations.CreateModel(
            name='SysUserDashboardBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsx', models.IntegerField(blank=True, null=True)),
                ('gsy', models.IntegerField(blank=True, null=True)),
                ('gsw', models.IntegerField(blank=True, null=True)),
                ('gsh', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('dashboard_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysdashboardblock')),
                ('dashboardid', models.ForeignKey(blank=True, db_column='dashboardid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysdashboard')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_dashboard_block',
            },
        ),
        migrations.CreateModel(
            name='SysUserFieldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldorder', models.IntegerField(blank=True, null=True)),
                ('typepreference', models.CharField(blank=True, max_length=32, null=True)),
                ('fieldid', models.ForeignKey(blank=True, db_column='fieldid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysfield')),
                ('master_tableid', models.ForeignKey(blank=True, db_column='master_tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sysuserfieldorder_master_tableid_set', to='commonapp.systable')),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_field_order',
            },
        ),
        migrations.CreateModel(
            name='SysUserFieldSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.CharField(blank=True, max_length=255, null=True)),
                ('fieldid', models.CharField(blank=True, max_length=32, null=True)),
                ('settingid', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('context', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_field_settings',
            },
        ),
        migrations.CreateModel(
            name='SysUserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldid', models.CharField(blank=True, max_length=32, null=True)),
                ('fieldorder', models.IntegerField(blank=True, null=True)),
                ('typepreference', models.CharField(blank=True, max_length=32, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_order',
            },
        ),
        migrations.CreateModel(
            name='SysUserPermission',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('permissionid', models.IntegerField()),
                ('enabled', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'sys_user_permission',
                'unique_together': {('userid', 'permissionid')},
            },
        ),
        migrations.CreateModel(
            name='SysUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_settings',
            },
        ),
        migrations.CreateModel(
            name='SysUserTableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableorder', models.IntegerField(blank=True, null=True)),
                ('typepreference', models.CharField(blank=True, max_length=255, null=True)),
                ('master_tableid', models.ForeignKey(blank=True, db_column='master_tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sysusertableorder_master_tableid_set', to='commonapp.systable')),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_table_order',
            },
        ),
        migrations.CreateModel(
            name='SysUserTableSearchField',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('tableid', models.CharField(max_length=32)),
                ('linkedtableid', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedmastetableid', models.CharField(blank=True, max_length=50, null=True)),
                ('fieldid', models.CharField(max_length=32)),
                ('fieldorder', models.IntegerField()),
            ],
            options={
                'db_table': 'sys_user_table_search_field',
                'unique_together': {('userid', 'tableid', 'fieldid')},
            },
        ),
        migrations.CreateModel(
            name='SysUserTableSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingid', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_user_table_settings',
            },
        ),
        migrations.CreateModel(
            name='SysView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('creation', models.DateTimeField(blank=True, null=True)),
                ('query_conditions', models.TextField(blank=True, null=True)),
                ('order_field', models.CharField(blank=True, max_length=255, null=True)),
                ('order_ascdesc', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_view',
            },
        ),
        migrations.CreateModel(
            name='SysUserDefaultView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
                ('userid', models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
                ('viewid', models.ForeignKey(blank=True, db_column='viewid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysview')),
            ],
            options={
                'db_table': 'sys_user_default_view',
            },
        ),
        migrations.AddField(
            model_name='sysdashboardblock',
            name='viewid',
            field=models.ForeignKey(blank=True, db_column='viewid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysview'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SysGroupUser',
            fields=[
                ('groupid', models.IntegerField(primary_key=True, serialize=False)),
                ('disabled', models.CharField(blank=True, max_length=1, null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser')),
            ],
            options={
                'db_table': 'sys_group_user',
                'unique_together': {('groupid', 'userid')},
            },
        ),
        migrations.CreateModel(
            name='SysTableLink',
            fields=[
                ('tableid', models.OneToOneField(db_column='tableid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='commonapp.systable')),
                ('tablelinkid', models.ForeignKey(db_column='tablelinkid', on_delete=django.db.models.deletion.DO_NOTHING, related_name='systablelink_tablelinkid_set', to='commonapp.systable')),
            ],
            options={
                'db_table': 'sys_table_link',
                'unique_together': {('tableid', 'tablelinkid')},
            },
        ),
    ]
