# Generated by Django 5.0.9 on 2025-09-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysCustomFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(choices=[('results', 'Results'), ('card', 'Card')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('backend_app', models.CharField(max_length=100)),
                ('backend_function', models.CharField(max_length=100)),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
            ],
            options={
                'verbose_name': 'Custom Function',
                'verbose_name_plural': 'Custom Functions',
                'db_table': 'sys_custom_function',
            },
        ),
    ]
