# Generated by Django 5.0.9 on 2025-09-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_syscustomfunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('layout', models.CharField(max_length=100)),
                ('config', models.JSONField()),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='commonapp.sysuser')),
            ],
            options={
                'verbose_name': 'Grafico',
                'verbose_name_plural': 'Grafici',
                'db_table': 'sys_chart',
            },
        ),
    ]
