# Generated by Django 5.0.9 on 2025-03-06 10:29

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='otp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
