# Generated by Django 5.0.9 on 2025-09-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0003_syschart'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysdashboardblock',
            name='chartid',
            field=models.ForeignKey(blank=True, db_column='chartid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.syschart'),
        ),
        migrations.AlterField(
            model_name='syschart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
