# Generated by Django 5.0.9 on 2025-09-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0004_sysdashboardblock_chartid_alter_syschart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syscustomfunction',
            old_name='backend_function',
            new_name='function',
        ),
        migrations.RemoveField(
            model_name='syscustomfunction',
            name='backend_app',
        ),
        migrations.AddField(
            model_name='syscustomfunction',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syscustomfunction',
            name='params',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
