# Generated by Django 5.0.9 on 2025-09-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0005_rename_backend_function_syscustomfunction_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysdashboard',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sysdashboardblock',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
