# Generated by Django 5.0.9 on 2025-10-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0006_sysdashboard_category_sysdashboardblock_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(blank=True, choices=[('campi', 'Campi'), ('allegati', 'Allegati'), ('collegate', 'Tabelle collegate'), ('aggiuntivi', 'Campi aggiuntivi')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Step di sistema',
                'verbose_name_plural': 'Steps di sistema',
                'db_table': 'sys_steps',
            },
        ),
        migrations.AddField(
            model_name='sysuserfieldorder',
            name='step_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonapp.sysstep'),
        ),
        migrations.CreateModel(
            name='SysStepTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.sysstep')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commonapp.systable')),
            ],
            options={
                'verbose_name': 'Associazione Step-Tabella',
                'verbose_name_plural': 'Associazioni Step-Tabella',
                'db_table': 'sys_steps_tables',
                'ordering': ['order'],
                'unique_together': {('step', 'table')},
            },
        ),
        migrations.AddField(
            model_name='sysstep',
            name='tables',
            field=models.ManyToManyField(related_name='steps', through='commonapp.SysStepTable', to='commonapp.systable'),
        ),
    ]
