# Generated by Django 5.0.9 on 2025-10-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0007_sysstep_sysuserfieldorder_step_name_syssteptable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syssteptable',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commonapp.sysuser'),
        ),
    ]
