# Generated by Django 5.0.9 on 2025-10-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0008_syssteptable_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuserfieldorder',
            old_name='step_name',
            new_name='step',
        ),
        migrations.AlterUniqueTogether(
            name='syssteptable',
            unique_together={('step', 'table', 'user')},
        ),
    ]
