# Generated by Django 5.0.9 on 2025-10-17 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0009_rename_step_name_sysuserfieldorder_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuserorder',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commonapp.sysstep'),
        ),
    ]
