# Generated by Django 5.0.9 on 2025-10-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0010_sysuserorder_step'),
    ]

    operations = [
    ]
