# Generated by Django 5.0.9 on 2025-10-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0011_auto_20251029_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChart',
            fields=[
                ('record_id', models.CharField(db_column='recordid_', max_length=32, primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(blank=True, db_column='creatorid_', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creation_', null=True)),
                ('last_updater_id', models.IntegerField(blank=True, db_column='lastupdaterid_', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='lastupdate_', null=True)),
                ('total_pages', models.IntegerField(blank=True, db_column='totpages_', null=True)),
                ('first_page_filename', models.CharField(blank=True, db_column='firstpagefilename_', max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, db_column='recordstatus_', max_length=255, null=True)),
                ('deleted_flag', models.CharField(db_column='deleted_', db_default='N', default='N', max_length=1)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('campi', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamicfield1', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamicfield1_label', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=255, null=True)),
                ('raggruppamento', models.CharField(blank=True, max_length=255, null=True)),
                ('tiporaggruppamento', models.CharField(blank=True, max_length=255, null=True)),
                ('pivot_total_field', models.CharField(blank=True, max_length=255, null=True)),
                ('campi2', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamicfield2', models.CharField(blank=True, max_length=255, null=True)),
                ('dynamicfield2_label', models.CharField(blank=True, max_length=255, null=True)),
                ('operation2', models.CharField(blank=True, max_length=255, null=True)),
                ('operation2_total', models.CharField(blank=True, max_length=255, null=True)),
                ('icona', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('reportid', models.CharField(blank=True, max_length=255, null=True)),
                ('tabella', models.CharField(blank=True, max_length=255, null=True)),
                ('dashboards', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.CharField(blank=True, max_length=255, null=True)),
                ('date_granularity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_chart',
            },
        ),
    ]
