# Generated by Django 5.0.9 on 2025-10-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0012_userchart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchart',
            old_name='dynamicfield1',
            new_name='dynamic_field_1',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='dynamicfield2',
            new_name='dynamic_field_2',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='dynamicfield2_label',
            new_name='dynamic_field_2_label',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='campi',
            new_name='fields',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='campi2',
            new_name='fields_2',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='raggruppamento',
            new_name='grouping',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='tiporaggruppamento',
            new_name='grouping_type',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='icona',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='reportid',
            new_name='report_id',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='tabella',
            new_name='table_name',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='descrizione',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userchart',
            old_name='dynamicfield1_label',
            new_name='dynamic_field_1_label',
        ),
    ]
