# Generated by Django 5.0.9 on 2025-10-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0013_rename_dynamicfield1_userchart_dynamic_field_1_and_more'),
    ]

    operations = [
    ]
