# Generated by Django 5.0.9 on 2025-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0014_auto_20251029_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('record_id', models.CharField(db_column='recordid_', max_length=32, primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(blank=True, db_column='creatorid_', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creation_', null=True)),
                ('last_updater_id', models.IntegerField(blank=True, db_column='lastupdaterid_', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='lastupdate_', null=True)),
                ('total_pages', models.IntegerField(blank=True, db_column='totpages_', null=True)),
                ('first_page_filename', models.CharField(blank=True, db_column='firstpagefilename_', max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, db_column='recordstatus_', max_length=255, null=True)),
                ('deleted_flag', models.CharField(db_column='deleted_', db_default='N', default='N', max_length=1)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('recipients', models.CharField(blank=True, max_length=255, null=True)),
                ('mailbody', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('sent_timestamp', models.CharField(blank=True, max_length=255, null=True)),
                ('cc', models.CharField(blank=True, max_length=255, null=True)),
                ('ccn', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_email',
            },
        ),
        migrations.AlterField(
            model_name='userchart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
