# Generated by Django 5.0.9 on 2025-10-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0017_usersystemlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersystemlog',
            old_name='note',
            new_name='output',
        ),
        migrations.RenameField(
            model_name='usersystemlog',
            old_name='hour',
            new_name='time',
        ),
    ]
