# Generated by Django 5.0.9 on 2025-10-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0020_userevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userevents',
            old_name='graphid',
            new_name='graph_event_id',
        ),
        migrations.RenameField(
            model_name='userevents',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='event_time',
        ),
        migrations.AddField(
            model_name='userevents',
            name='body_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='calendar_delta_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='m365_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
