# Generated by Django 5.0.9 on 2025-10-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0021_rename_graphid_userevents_graph_event_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevents',
            options={'verbose_name_plural': 'Eventi'},
        ),
    ]
