# Generated by Django 5.0.9 on 2025-10-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0023_userattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevents',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
