# Generated by Django 5.0.9 on 2025-10-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0023_userattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchart',
            options={'verbose_name_plural': 'Grafici'},
        ),
        migrations.AlterModelOptions(
            name='useremail',
            options={'verbose_name_plural': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='userschedulerlog',
            options={'verbose_name_plural': 'Log scheduler'},
        ),
        migrations.AlterModelOptions(
            name='usersystemlog',
            options={'verbose_name_plural': 'Log sistema'},
        ),
        migrations.AlterModelOptions(
            name='useruserlog',
            options={'verbose_name_plural': 'Log utente'},
        ),
    ]
