# Generated by Django 5.0.9 on 2025-11-03 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0025_userevents_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='syschart',
            name='function_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.syscustomfunction'),
        ),
        migrations.AddField(
            model_name='userchart',
            name='function_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.syscustomfunction'),
        ),
    ]
