# Generated by Django 5.0.9 on 2025-11-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0026_syschart_function_button_userchart_function_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syschart',
            name='function_button',
            field=models.ForeignKey(blank=True, db_column='function_button', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.syscustomfunction'),
        ),
        migrations.AlterField(
            model_name='userchart',
            name='function_button',
            field=models.ForeignKey(blank=True, db_column='function_button', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.syscustomfunction'),
        ),
    ]
