# Generated by Django 5.0.9 on 2025-11-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0027_alter_syschart_function_button_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevents',
            name='table',
            field=models.ForeignKey(blank=True, db_column='table', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable'),
        ),
        migrations.AlterField(
            model_name='userevents',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser'),
        ),
    ]
