# Generated by Django 5.0.9 on 2025-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0028_alter_userevents_table_alter_userevents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevents',
            name='recordidtable',
            field=models.CharField(blank=True, db_column='recordidtable', max_length=255, null=True),
        ),
    ]
