# Generated by Django 5.0.9 on 2025-11-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0029_userevents_recordidtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevents',
            name='table',
        ),
        migrations.RemoveField(
            model_name='userevents',
            name='user',
        ),
        migrations.AddField(
            model_name='userevents',
            name='tableid',
            field=models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable'),
        ),
        migrations.AddField(
            model_name='userevents',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser'),
        ),
    ]
