# Generated by Django 5.0.9 on 2025-11-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0030_remove_userevents_table_remove_userevents_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattachment',
            name='_recordiddeal',
        ),
        migrations.RemoveField(
            model_name='userattachment',
            name='recordiddeal',
        ),
    ]
