# Generated by Django 5.0.9 on 2025-11-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0031_remove_userattachment__recordiddeal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchart',
            name='category_dashboard',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userchart',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
