# Generated by Django 5.0.9 on 2025-11-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0032_userchart_category_dashboard_userchart_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='syschart',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
