# Generated by Django 5.0.9 on 2025-11-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0033_syschart_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useremail',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
