# Generated by Django 5.0.9 on 2025-12-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0034_useremail_attachment_useremail_attachment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobStatus',
            fields=[
                ('record_id', models.CharField(db_column='recordid_', max_length=32, primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(blank=True, db_column='creatorid_', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creation_', null=True)),
                ('last_updater_id', models.IntegerField(blank=True, db_column='lastupdaterid_', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='lastupdate_', null=True)),
                ('total_pages', models.IntegerField(blank=True, db_column='totpages_', null=True)),
                ('first_page_filename', models.CharField(blank=True, db_column='firstpagefilename_', max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, db_column='recordstatus_', max_length=255, null=True)),
                ('deleted_flag', models.CharField(db_column='deleted_', db_default='N', default='N', max_length=1)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('sourcenote', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('creationdate', models.DateField(blank=True, null=True)),
                ('closedate', models.DateField(blank=True, null=True)),
                ('technote', models.TextField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stato Lavori',
                'db_table': 'user_job_status',
            },
        ),
    ]
