# Generated by Django 5.0.9 on 2025-12-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0035_userjobstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMonitoring',
            fields=[
                ('record_id', models.CharField(db_column='recordid_', max_length=32, primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(blank=True, db_column='creatorid_', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creation_', null=True)),
                ('last_updater_id', models.IntegerField(blank=True, db_column='lastupdaterid_', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='lastupdate_', null=True)),
                ('total_pages', models.IntegerField(blank=True, db_column='totpages_', null=True)),
                ('first_page_filename', models.CharField(blank=True, db_column='firstpagefilename_', max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, db_column='recordstatus_', max_length=255, null=True)),
                ('deleted_flag', models.CharField(db_column='deleted_', db_default='N', default='N', max_length=1)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hour', models.CharField(blank=True, max_length=255, null=True)),
                ('clientid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('monitoring_output', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Monitoring',
                'db_table': 'user_monitoring',
            },
        ),
        migrations.AddField(
            model_name='userschedulerlog',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
