# Generated by Django 5.0.9 on 2025-12-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0036_usermonitoring_userschedulerlog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobstatus',
            name='clientid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
