# Generated by Django 5.0.9 on 2025-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0037_userjobstatus_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonitoring',
            name='scheduleid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
