# Generated by Django 5.0.9 on 2025-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0038_usermonitoring_scheduleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobstatus',
            name='duration',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userjobstatus',
            name='reporter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userjobstatus',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
