# Generated by Django 5.0.9 on 2025-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0039_userjobstatus_duration_userjobstatus_reporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuserfieldsettings',
            name='conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sysusertablesettings',
            name='conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userjobstatus',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
