# Generated by Django 5.0.9 on 2025-12-22 08:31

import datetime
import os
from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Leggiamo le credenziali dalle variabili d'ambiente
    # Il secondo parametro è un valore di default (opzionale)
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    first_name = os.environ.get('DJANGO_SUPERUSER_FIRST_NAME', 'top')
    last_name = os.environ.get('DJANGO_SUPERUSER_LAST_NAME', 'superuser')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

    if not password:
        print("\nErrore: DJANGO_SUPERUSER_PASSWORD non trovata nel file .env. Utente non creato.")
        return

    # Verifichiamo se l'utente esiste già
    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            password=make_password(password),
            is_superuser=True,
            is_staff=True
        )
        print(f"\nSuperuser '{username}' creato con successo.")
    else:
        print(f"\nSuperuser '{username}' già esistente.")

    sys_user_password = os.environ.get('SYS_USER_PASSWORD')
    creation_date = datetime.datetime.now()

    # Create User
    sys_user = apps.get_model('commonapp', 'SysUser')
    if not sys_user.objects.filter(username=username).exists():
        sys_user.objects.create(
            id=1,
            firstname='Super',
            lastname='User',
            description="JDoc Superuser",
            username=username,
            password=sys_user_password,
            email="support@about-x.com",
            disabled="N",
            superuser="Y",
            enablesendmail=0,
            bixid=1,
            creationdate=creation_date,
        )

    user = sys_user.objects.get(username=username)

    # Create theme setting
    sys_user_settings = apps.get_model('commonapp', 'SysUserSettings')
    
    if not sys_user_settings.objects.filter(setting='theme').exists():
        sys_user_settings.objects.create(
            userid=user,
            setting='theme',
            value='oceanic'
        )



def remove_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    User.objects.filter(username=username).delete()

    sys_user = apps.get_model('commonapp', 'SysUser')
    user = sys_user.objects.get(username=username)

    sys_user_settings = apps.get_model('commonapp', 'SysUserSettings')
    sys_user_settings.objects.filter(setting='theme', userid=user).delete()
    
    sys_user = apps.get_model('commonapp', 'SysUser')
    user.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0040_sysuserfieldsettings_conditions_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_code=remove_superuser),
    ]
