# Generated by Django 5.0.9 on 2025-12-22 08:42

import os
from django.db import migrations

def create_initial_settings(apps, schema_editor):
    SysSetting = apps.get_model('commonapp', 'SysSettings')

    client_id = os.environ.get('CLIENT_ID')
    client_name = os.environ.get('CLIENT_NAME')

    if not SysSetting.objects.filter(setting='cliente_id').exists():
        SysSetting.objects.create(
            id=0,
            setting='cliente_id',
            value=client_id
        )

    if not SysSetting.objects.filter(setting='cliente_nome').exists():
        SysSetting.objects.create(
            id=1,
            setting='cliente_nome',
            value=client_name
        )

def rollback_initial_setup(apps, schema_editor):
    SysSetting = apps.get_model('commonapp', 'SysSettings')
    SysSetting.objects.filter(setting='cliente_id').delete()
    SysSetting.objects.filter(setting='cliente_nome').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0041_create_initial_admin')
    ]

    operations = [
         migrations.RunPython(create_initial_settings, reverse_code=rollback_initial_setup),
    ]
