# Generated by Django - Custom Migration for Database Views
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        # Questa migration deve avvenire DOPO la creazione dell'utente e delle tabelle base
        ('commonapp', '0042_create_initial_settings'), 
        ('auth', '__latest__'),
    ]

    operations = [
        # --- 1. VISTA: v_users ---
        # Collega l'utente Django (auth_user) con la tua tabella personalizzata (sys_user)
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW `v_users` AS 
            SELECT 
                `sys_user`.`id` AS `sys_user_id`,
                `auth_user`.`id` AS `id`,
                `auth_user`.`password` AS `password`,
                `auth_user`.`last_login` AS `last_login`,
                `auth_user`.`is_superuser` AS `is_superuser`,
                `auth_user`.`username` AS `username`,
                `auth_user`.`first_name` AS `first_name`,
                `auth_user`.`last_name` AS `last_name`,
                `auth_user`.`email` AS `email`,
                `auth_user`.`is_staff` AS `is_staff`,
                `auth_user`.`is_active` AS `is_active`,
                `auth_user`.`date_joined` AS `date_joined` 
            FROM `auth_user` 
            LEFT JOIN `sys_user` ON `auth_user`.`id` = `sys_user`.`bixid`;
            """,
            reverse_sql="DROP VIEW IF EXISTS `v_users`;"
        ),

        # --- 2. VISTA: v_sys_user_settings ---
        # Gestisce le impostazioni generali dell'utente
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW `v_sys_user_settings` AS 
            SELECT 
                `sys_user`.`bixid` AS `bixid`,
                `sys_user_settings`.`id` AS `id`,
                `sys_user_settings`.`userid` AS `userid`,
                `sys_user_settings`.`setting` AS `setting`,
                `sys_user_settings`.`value` AS `value` 
            FROM `sys_user_settings` 
            LEFT JOIN `sys_user` ON `sys_user_settings`.`userid` = `sys_user`.`id`;
            """,
            reverse_sql="DROP VIEW IF EXISTS `v_sys_user_settings`;"
        ),

        # --- 3. VISTA: v_sys_user_table_settings ---
        # Gestisce le impostazioni specifiche delle tabelle per ogni utente
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE VIEW `v_sys_user_table_settings` AS 
            SELECT 
                `sys_user`.`bixid` AS `bixid`,
                `sys_user_table_settings`.`id` AS `id`,
                `sys_user_table_settings`.`userid` AS `userid`,
                `sys_user_table_settings`.`tableid` AS `tableid`,
                `sys_user_table_settings`.`settingid` AS `settingid`,
                `sys_user_table_settings`.`value` AS `value` 
            FROM `sys_user_table_settings` 
            LEFT JOIN `sys_user` ON `sys_user_table_settings`.`userid` = `sys_user`.`id`;
            """,
            reverse_sql="DROP VIEW IF EXISTS `v_sys_user_table_settings`;"
        ),
    ]