# Generated by Django 5.0.9 on 2026-02-11 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0043_fix_composite_pkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeadline',
            fields=[
                ('record_id', models.CharField(db_column='recordid_', max_length=32, primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField(blank=True, db_column='creatorid_', null=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='creation_', null=True)),
                ('last_updater_id', models.IntegerField(blank=True, db_column='lastupdaterid_', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='lastupdate_', null=True)),
                ('total_pages', models.IntegerField(blank=True, db_column='totpages_', null=True)),
                ('first_page_filename', models.CharField(blank=True, db_column='firstpagefilename_', max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, db_column='recordstatus_', max_length=255, null=True)),
                ('deleted_flag', models.CharField(db_column='deleted_', db_default='N', default='N', max_length=1)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('recordidtable', models.CharField(blank=True, db_column='recordidtable', max_length=255, null=True)),
                ('date_deadline', models.DateField(blank=True, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency_months', models.CharField(blank=True, max_length=255, null=True)),
                ('actions', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_days', models.IntegerField(blank=True, null=True)),
                ('tableid', models.ForeignKey(blank=True, db_column='tableid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.systable')),
            ],
            options={
                'verbose_name_plural': 'Scadenze',
                'db_table': 'user_deadline',
            },
        ),
    ]
