# Generated by Django 5.0.9 on 2026-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0044_userdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattachment',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userchart',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userdeadline',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='useremail',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userjobstatus',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='usermonitoring',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userschedulerlog',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='usersystemlog',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
    ]
