# Generated by Django 5.0.9 on 2026-02-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    # QUERY Controlla quali tabelle hanno linkedorder_
    # SELECT 
    #     table_schema,
    #     table_name, 
    #     column_name
    # FROM 
    #     information_schema.columns 
    # WHERE 
    #     table_name IN (
    #         'user_attachment', 'user_chart', 'user_deadline', 
    #         'user_email', 'user_events', 'user_job_status', 
    #         'user_monitoring', 'user_scheduler_log', 
    #         'user_system_log', 'user_user_log'
    #     ) 
    #     AND column_name = 'linkedorder_'
    #     -- Questo serve a guardare solo il database in cui sei connesso
    #     AND table_schema NOT IN ('information_schema', 'pg_catalog');


    dependencies = [
        ('commonapp', '0044_userdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattachment',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userchart',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userdeadline',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='useremail',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userevents',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userjobstatus',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='usermonitoring',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='userschedulerlog',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='usersystemlog',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='linked_order',
            field=models.IntegerField(blank=True, db_column='linkedorder_', null=True),
        ),
    ]
