# Generated by Django 5.0.9 on 2026-02-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0045_userattachment_linked_order_userchart_linked_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeadline',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_column='assigned_to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser'),
        ),
        migrations.AddField(
            model_name='userdeadline',
            name='notification_sent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
