# Generated by Django 5.0.9 on 2026-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0046_userdeadline_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobstatus',
            name='deploydate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
