# Generated by Django 5.0.9 on 2026-04-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0047_userjobstatus_deploydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysgroup',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
