# Generated by Django 5.0.9 on 2026-05-11

from django.db import migrations

def update_system_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    SysUser = apps.get_model('commonapp', 'SysUser')

    # 1. Definisci qui i nuovi dati standard e fissi per l'utente di sistema
    nuovi_dati = {
        'username': 'default',
        'first_name': 'Default',
        'last_name': 'User',
        'email': 'support@bixdata.ch',
        'description': 'BixData Default User',
    }

    # 2. Cerchiamo il SysUser tramite la sua unica certezza: id=1
    sys_users = SysUser.objects.filter(id=1)

    if sys_users.exists():
        sys_user_obj = sys_users.first()
        vecchio_username = sys_user_obj.username
        user_bixid = sys_user_obj.bixid

        # 3. Aggiorniamo il modello standard User di Django tramite l'ID (bixid)
        if user_bixid is not None:
            User.objects.filter(id=user_bixid).update(
                username=nuovi_dati['username'],
                first_name=nuovi_dati['first_name'],
                last_name=nuovi_dati['last_name'],
                email=nuovi_dati['email']
            )
        else:
            # Fallback di emergenza se per qualche motivo bixid fosse nullo
            User.objects.filter(username=vecchio_username).update(
                username=nuovi_dati['username'],
                first_name=nuovi_dati['first_name'],
                last_name=nuovi_dati['last_name'],
                email=nuovi_dati['email']
            )

        # 4. Aggiorniamo il modello custom SysUser
        sys_users.update(
            username=nuovi_dati['username'],
            firstname=nuovi_dati['first_name'],
            lastname=nuovi_dati['last_name'],
            description=nuovi_dati['description'],
            email=nuovi_dati['email']
        )
        
        print(f"\n[OK] Utente di sistema (ID 1) aggiornato. Username cambiato da '{vecchio_username}' a '{nuovi_dati['username']}'.")
    else:
        # Se per qualche motivo il DB è vuoto o corrotto e l'ID 1 non c'è, non andiamo in crash.
        print("\n[SKIP] Nessun SysUser con ID=1 trovato nel database. Nessuna modifica effettuata.")

def revert_system_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    SysUser = apps.get_model('commonapp', 'SysUser')

    # Dati per il ripristino in caso di Rollback (es. migrate nome_app 0041)
    dati_ripristino = {
        'username': 'admin',
        'first_name': 'top',
        'last_name': 'superuser',
        'email': 'support@about-x.com',
        'description': 'JDoc Superuser',
    }

    sys_users = SysUser.objects.filter(id=1)
    if sys_users.exists():
        sys_user_obj = sys_users.first()
        user_bixid = sys_user_obj.bixid
        
        if user_bixid is not None:
            User.objects.filter(id=user_bixid).update(
                username=dati_ripristino['username'],
                first_name=dati_ripristino['first_name'],
                last_name=dati_ripristino['last_name'],
                email=dati_ripristino['email']
            )
        else:
            attuale_username = sys_user_obj.username
            User.objects.filter(username=attuale_username).update(
                username=dati_ripristino['username'],
                first_name=dati_ripristino['first_name'],
                last_name=dati_ripristino['last_name'],
                email=dati_ripristino['email']
            )

        sys_users.update(
            username=dati_ripristino['username'],
            firstname=dati_ripristino['first_name'],
            lastname=dati_ripristino['last_name'],
            description=dati_ripristino['description'],
            email=dati_ripristino['email']
        )

class Migration(migrations.Migration):

    dependencies = [
        # Inserisci qui il nome esatto del file della TUA migrazione precedente
        ('commonapp', '0048_sysgroup_priority'),
    ]

    operations = [
        migrations.RunPython(update_system_user, reverse_code=revert_system_user),
    ]