# Generated by Django 5.0.9 on 2026-05-11 07:32

from django.db import migrations
from django.utils import timezone
from django.db.models import Max

def create_or_update_admin_and_group(apps, schema_editor):
    SysUser = apps.get_model('commonapp', 'SysUser')
    SysGroup = apps.get_model('commonapp', 'SysGroup')
    SysGroupUser = apps.get_model('commonapp', 'SysGroupUser')

    tabelle_dipendenti = [
        'SysUserSettings', 'SysUserTableSettings',
        'SysUserTableOrder', 'SysUserFieldOrder', 'SysUserFieldSettings'
    ]

    # --- FASE 1: SGOMBERIAMO L'ID 0 SE OCCUPATO DA UN ALTRO UTENTE ---
    user_at_zero = SysUser.objects.filter(id=0).first()
    
    if user_at_zero and user_at_zero.username != 'group.admin':
        max_id = SysUser.objects.aggregate(Max('id'))['id__max']
        nuovo_id_libero = (max_id or 0) + 1

        vecchio_username = user_at_zero.username
        SysUser.objects.filter(id=0).update(username=f"temp_{vecchio_username}")

        # Cloniamo l'utente sul nuovo ID
        user_to_move = SysUser.objects.get(id=0)
        user_to_move.pk = nuovo_id_libero
        user_to_move.id = nuovo_id_libero
        user_to_move.username = vecchio_username
        
        # FIX: Assicuriamoci che la data di creazione non sia nulla prima dell'INSERT
        if not user_to_move.creationdate:
            user_to_move.creationdate = timezone.now()

        user_to_move.save(force_insert=True)

        # Spostiamo i SUOI settings al nuovo ID
        for model_name in tabelle_dipendenti:
            try:
                SettingsModel = apps.get_model('commonapp', model_name)
                SettingsModel.objects.filter(userid=0).update(userid=user_to_move)
            except LookupError:
                pass
        
        SysGroup.objects.filter(idmanager=0).update(idmanager=user_to_move)
        SysGroupUser.objects.filter(userid=0).update(userid=user_to_move)

        SysUser.objects.filter(id=0).delete()
        print(f"\n[ATTENZIONE] ID 0 era occupato da '{vecchio_username}'. Spostato all'ID {nuovo_id_libero}.")

    # --- FASE 2: GESTIAMO GROUP.ADMIN ---
    group_admin = SysUser.objects.filter(username='group.admin').first()

    if group_admin:
        if group_admin.id == 0:
            SysUser.objects.filter(id=0).update(
                firstname='Group', lastname='Admin', description='System Group Administrator',
                email='group.admin@bixdata.ch', disabled='N', superuser='Y'
            )
            new_sys_user = SysUser.objects.get(id=0)
            print("\n[OK] Utente 'group.admin' già presente all'ID 0. Dati aggiornati.")
        else:
            old_id = group_admin.id
            
            # Cloniamo group.admin all'ID 0
            group_admin.pk = 0
            group_admin.id = 0
            
            # FIX: Assicuriamoci che la data di creazione non sia nulla prima dell'INSERT
            if not group_admin.creationdate:
                group_admin.creationdate = timezone.now()

            group_admin.save(force_insert=True)
            new_sys_user = SysUser.objects.get(id=0)

            for model_name in tabelle_dipendenti:
                try:
                    SettingsModel = apps.get_model('commonapp', model_name)
                    SettingsModel.objects.filter(userid=old_id).update(userid=new_sys_user)
                except LookupError:
                    pass
            
            SysGroup.objects.filter(idmanager=old_id).update(idmanager=new_sys_user)
            SysGroupUser.objects.filter(userid=old_id).update(userid=new_sys_user)

            SysUser.objects.filter(id=old_id).delete()
            print(f"\n[OK] 'group.admin' spostato dall'ID {old_id} all'ID 0. Settings conservati!")
            
    else:
        new_sys_user = SysUser.objects.create(
            id=0, username='group.admin', firstname='Group', lastname='Admin',
            description='System Group Administrator', email='group.admin@bixdata.ch',
            creationdate=timezone.now(), disabled='N', superuser='Y'
        )
        print("\n[OK] Nuovo 'group.admin' creato all'ID 0.")

    # --- FASE 3: ASSOCIAZIONE AL GRUPPO ADMIN ---
    group, group_created = SysGroup.objects.get_or_create(
        name='admin',
        defaults={
            'description': 'Gruppo Amministratori',
            'idmanager': new_sys_user,
            'creatorid': 0,
            'creationdate': timezone.now(),
            'disabled': 'N',
            'priority': 1
        }
    )

    if not group_created and group.idmanager != new_sys_user:
        group.idmanager = new_sys_user
        group.save()
        print("\n[OK] SysGroup 'admin' aggiornato: manager impostato su ID 0.")

    group_user, gu_created = SysGroupUser.objects.get_or_create(
        groupid=group.id,
        userid=new_sys_user,
        defaults={'disabled': 'N'}
    )
    
    if gu_created:
        print(f"\n[OK] Utente ID 0 associato correttamente al gruppo ID {group.id}.")


def do_nothing(apps, schema_editor):
    # Un rollback distruggerebbe il trasferimento ID appena fatto.
    # Meglio un pass per non corrompere le ForeignKey.
    pass


class Migration(migrations.Migration):

    dependencies = [
        # ATTENZIONE: Assicurati che qui ci sia la tua migrazione precedente
        ('commonapp', '0049_update_admin_to_default'), 
    ]

    operations = [
        migrations.RunPython(
            create_or_update_admin_and_group, 
            reverse_code=do_nothing
        ),
    ]