# Generated by Django 5.0.9 on 2026-05-19 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0050_create_group_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useruserlog',
            name='function',
        ),
        migrations.RemoveField(
            model_name='useruserlog',
            name='output',
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='action_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='log_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='new_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='old_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='recordidtable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useruserlog',
            name='tableid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useruserlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='commonapp.sysuser'),
        ),
    ]
