# Generated by Django 5.0.9 on 2026-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonapp', '0051_remove_useruserlog_function_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysPartial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_recordid', models.CharField(blank=True, max_length=255, null=True)),
                ('tableid', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.IntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sys_partial',
            },
        ),
    ]
